### ISSUE TITLE
1.18.2-2.0.12+8fbc9f4-beta 初始化阶段报错

### ISSUE THREAD

**Issue by xiaoyv404** [Hendrix-Shen/Bilibili-Danmaku#1]
[错误报告-2022-12-27_10.56.48.zip](https://github.com/Hendrix-Shen/Bilibili-Danmaku/files/10305575/-2022-12-27_10.56.48.zip)

**Comment by Hendrix-Shen** [comment]
试一下 [2.0.13+0aaac10](https://github.com/Hendrix-Shen/Bilibili-Danmaku/releases/tag/CI%2Fbuild.13)

**Comment by xiaoyv404** [comment]
fixed
